# Generated by Django 5.0.6 on 2024-10-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellitetle',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
