# Generated by Django 5.0.6 on 2025-01-16 13:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_userprofile"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="telemetrymodel",
            new_name="Telemetry D_timesta_be9519_idx",
            old_name="main_teleme_timesta_598313_idx",
        ),
        migrations.RenameIndex(
            model_name="telemetrymodel",
            new_name="Telemetry D_satelli_90db31_idx",
            old_name="main_teleme_satelli_bd3f8a_idx",
        ),
        migrations.AlterModelTable(
            name="telemetrymodel",
            table="Telemetry Data",
        ),
        migrations.AlterModelTable(
            name="userprofile",
            table="User Profile",
        ),
    ]
