# Generated by Django 5.0.6 on 2024-10-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_satellitetle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellitetle',
            name='line1',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='satellitetle',
            name='line2',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='satellitetle',
            unique_together={('name', 'line1', 'line2')},
        ),
        migrations.CreateModel(
            name='SatellitePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('satellite_name', models.CharField(max_length=255)),
                ('pass_time', models.DateTimeField()),
                ('max_elevation', models.FloatField()),
                ('azimuth', models.FloatField()),
                ('distance', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('satellite_name', 'pass_time')},
            },
        ),
    ]
