# Generated by Django 5.0.6 on 2024-10-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_satellitetle_line1_alter_satellitetle_line2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellitetle',
            name='line1',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='satellitetle',
            name='line2',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
