# Generated by Django 5.0.6 on 2025-01-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_main_teleme_timesta_598313_idx_telemetry_d_timesta_be9519_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellitetle',
            name='custom_tle_url',
            field=models.URLField(blank=True, help_text='A custom URL for TLE updates instead of using the default group URL.', max_length=500, null=True),
        ),
    ]
