# Generated by Django 5.0.6 on 2025-02-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_satellitetle_custom_tle_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="MissionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("rise_time", models.DateTimeField()),
                ("set_time", models.DateTimeField()),
                ("max_elevation", models.FloatField()),
                ("trajectory", models.JSONField()),
                ("orbiting_satellite", models.IntegerField()),
                ("min_elevation", models.PositiveIntegerField(default=10)),
                ("prediction_days", models.PositiveIntegerField(default=5)),
                ("sun_illumination", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "Mission Plan",
                "ordering": ["-created_at"],
            },
        ),
    ]
