# Generated by Django 5.0.6 on 2024-10-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_satellitetle_line1_alter_satellitetle_line2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='satellitepass',
            old_name='max_elevation',
            new_name='elevation',
        ),
        migrations.AlterUniqueTogether(
            name='satellitepass',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='satellitepass',
            name='event',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='satellitepass',
            unique_together={('satellite_name', 'pass_time', 'event')},
        ),
    ]
