# Generated by Django 5.0.6 on 2024-10-22 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_max_elevation_satellitepass_elevation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='satellitepass',
            old_name='elevation',
            new_name='max_elevation',
        ),
        migrations.RenameField(
            model_name='satellitepass',
            old_name='pass_time',
            new_name='set_pass_time',
        ),
        migrations.AlterUniqueTogether(
            name='satellitepass',
            unique_together={('satellite_name', 'set_pass_time')},
        ),
        migrations.RemoveField(
            model_name='satellitepass',
            name='event',
        ),
    ]
