# Generated by Django 5.0.6 on 2025-02-03 11:09

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_missionplan"),
    ]

    operations = [
        # Step 1: Create a temporary field to hold the transformed data
        migrations.AddField(
            model_name="missionplan",
            name="trajectory_temp",
            field=django.contrib.gis.db.models.fields.LineStringField(
                geography=True, srid=4326, null=True
            ),
        ),

        # Step 2: Run SQL to migrate data from the old 'trajectory' field (jsonb) to the new 'trajectory_temp' field
        migrations.RunSQL(
            """
            UPDATE "Mission Plan"
            SET trajectory_temp = ST_LineFromEncodedPolyline(trajectory::text)
            WHERE trajectory IS NOT NULL;
            """
        ),

        # Step 3: Drop the original field
        migrations.RemoveField(
            model_name="missionplan",
            name="trajectory",
        ),

        # Step 4: Rename the temporary field to the original name
        migrations.RenameField(
            model_name="missionplan",
            old_name="trajectory_temp",
            new_name="trajectory",
        ),

        # Step 5: Add the remaining operations
        migrations.RemoveField(
            model_name="missionplan",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="missionplan",
            name="longitude",
        ),
        migrations.AddField(
            model_name="missionplan",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                geography=True, null=True, srid=4326
            ),
        ),
    ]
