# Generated by Django 5.0.6 on 2025-02-03 14:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_remove_missionplan_latitude_and_more"),
    ]

    operations = []
