# Generated by Django 5.0.6 on 2024-10-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_elevation_satellitepass_max_elevation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellitepass',
            name='rise_pass_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
