# Generated by Django 5.0.6 on 2025-02-03 15:01

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_auto_20250203_1620"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missionplan",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name="missionplan",
            name="trajectory",
            field=django.contrib.gis.db.models.fields.LineStringField(
                null=True, srid=4326
            ),
        ),
    ]
