# Generated by Django 5.0.6 on 2024-10-22 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_satellitepass_rise_pass_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='satellitepass',
            unique_together={('satellite_name', 'rise_pass_time', 'set_pass_time')},
        ),
    ]
