# Generated by Django 5.0.6 on 2025-02-04 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_alter_missionplan_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missionplan",
            name="orbiting_satellite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mission_plans",
                to="main.satellitetle",
            ),
        ),
    ]
