# Generated by Django 5.0.6 on 2024-11-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_satellitepass_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroundStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name of the ground station', max_length=100, unique=True)),
                ('latitude', models.FloatField(help_text='Latitude of the ground station in decimal degrees')),
                ('longitude', models.FloatField(help_text='Longitude of the ground station in decimal degrees')),
                ('altitude', models.FloatField(help_text='Altitude of the ground station in meters above sea level')),
                ('start_tracking_elevation', models.FloatField(default=10.0, help_text='Minimum elevation angle (in degrees) above horizon to start tracking')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the ground station is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time the ground station was added')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time the ground station was last updated')),
            ],
            options={
                'verbose_name': 'Ground Station',
                'verbose_name_plural': 'Ground Stations',
            },
        ),
    ]
