# Generated by Django 5.0.6 on 2024-11-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_groundstation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groundstation',
            name='latitude',
            field=models.DecimalField(decimal_places=6, help_text='Latitude of the ground station in decimal degrees', max_digits=9),
        ),
        migrations.AlterField(
            model_name='groundstation',
            name='longitude',
            field=models.DecimalField(decimal_places=6, help_text='Longitude of the ground station in decimal degrees', max_digits=9),
        ),
        migrations.AlterUniqueTogether(
            name='groundstation',
            unique_together={('name', 'latitude', 'longitude')},
        ),
    ]
