# Generated by Django 5.0.6 on 2025-02-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="is_delivered",
            field=models.BooleanField(default=False),
        ),
    ]
