# Generated by Django 5.0.6 on 2024-11-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_groundstation_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellitetle',
            name='auto_tracking',
            field=models.BooleanField(default=False, help_text='Whether auto-tracking is enabled for this satellite.'),
        ),
        migrations.AddField(
            model_name='satellitetle',
            name='orbit_status',
            field=models.CharField(choices=[('orbiting', 'Orbiting'), ('de-orbited', 'De-orbited')], default='orbiting', help_text='The orbit status of the satellite.', max_length=20),
        ),
    ]
