# Generated by Django 5.0.6 on 2024-11-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_satellitetle_auto_tracking_satellitetle_orbit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellitetle',
            name='tle_group',
            field=models.CharField(choices=[('active', 'Active Satellites'), ('analyst', 'Analyst Satellites'), ('cubesat', 'CubeSats'), ('debris', 'Debris'), ('education', 'Education'), ('engineering', 'Engineering'), ('earthobs', 'Earth Observation'), ('galileo', 'Galileo'), ('geo', 'Geostationary'), ('glo-ops', 'GLONASS Operational'), ('glo-all', 'GLONASS All'), ('gps-ops', 'GPS Operational'), ('gps-all', 'GPS All'), ('geo-protected', 'Geostationary Protected Region'), ('geo-unregistered', 'Geostationary Unregistered'), ('intelsat', 'Intelsat Satellites'), ('iridium', 'Iridium Satellites'), ('military', 'Military Satellites'), ('other', 'Other Satellites'), ('planet', 'Planet Satellites'), ('science', 'Science Satellites'), ('stations', 'Stations'), ('starlink', 'Starlink'), ('tdrss', 'TDRSS'), ('weather', 'Weather Satellites')], default='weather', help_text='The TLE group from CelesTrak used for updating TLE data.', max_length=20),
        ),
    ]
