# Generated by Django 5.0.6 on 2025-02-19 04:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0011_chatmessage_is_delivered"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={"ordering": ("-timestamp",)},
        ),
        migrations.AlterModelTable(
            name="chatmessage",
            table="Chats",
        ),
    ]
