# Generated by Django 5.0.6 on 2024-12-15 05:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_satellitetle_tle_group"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="groundstation",
            table="Ground Station",
        ),
        migrations.AlterModelTable(
            name="satellitepass",
            table="Satellite Passes",
        ),
        migrations.AlterModelTable(
            name="satellitetle",
            table="Satellites",
        ),
    ]
