# Generated by Django 5.0.6 on 2025-02-21 11:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0012_alter_chatmessage_options_alter_chatmessage_table"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="room_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["sender", "receiver"], name="Chats_sender__350594_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["is_read", "is_delivered"], name="Chats_is_read_cab5c5_idx"
            ),
        ),
    ]
